//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities : DbContext
    {
        public DbCVEntities()
            : base("name=DbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_About> TBL_About { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Deneyimlerim> TBL_Deneyimlerim { get; set; }
        public virtual DbSet<TBL_Egitimlerim> TBL_Egitimlerim { get; set; }
        public virtual DbSet<TBL_Hobilerim> TBL_Hobilerim { get; set; }
        public virtual DbSet<TBL_Iletisim> TBL_Iletisim { get; set; }
        public virtual DbSet<TBL_Yeteneklerim> TBL_Yeteneklerim { get; set; }
        public virtual DbSet<TBL_Sertifikalarim1> TBL_Sertifikalarim1 { get; set; }
        public virtual DbSet<TBL_SosyalMedya> TBL_SosyalMedya { get; set; }
    }
}
